
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        uses: bilalalpaslan/my-gh-action@main
      
      - name: step-2
        run: ls -la