
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        uses: bilalAlpaslan/my-gh-action@master
        with:
          command: "deneme"
        
      

